/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import java.io.File;
import com.cloudmersive.client.gac.model.XmlAddAttributeWithXPathResult;
import com.cloudmersive.client.gac.model.XmlAddChildWithXPathResult;
import com.cloudmersive.client.gac.model.XmlFilterWithXPathResult;
import com.cloudmersive.client.gac.model.XmlQueryWithXQueryMultiResult;
import com.cloudmersive.client.gac.model.XmlQueryWithXQueryResult;
import com.cloudmersive.client.gac.model.XmlRemoveAllChildrenWithXPathResult;
import com.cloudmersive.client.gac.model.XmlRemoveWithXPathResult;
import com.cloudmersive.client.gac.model.XmlReplaceWithXPathResult;
import com.cloudmersive.client.gac.model.XmlSetValueWithXPathResult;
import org.junit.Test;
import org.junit.Ignore;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConvertDataApi
 */
@Ignore
public class ConvertDataApiTest {

    private final ConvertDataApi api = new ConvertDataApi();

    
    /**
     * Convert CSV to JSON conversion
     *
     * Convert a CSV file to a JSON object array
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataCsvToJsonTest() throws IOException {
        File inputFile = null;
        Boolean columnNamesFromFirstRow = null;
        Object response = api.convertDataCsvToJson(inputFile, columnNamesFromFirstRow);

        // TODO: test validations
    }
    
    /**
     * Convert CSV to XML conversion
     *
     * Convert a CSV file to a XML file
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataCsvToXmlTest() throws IOException {
        File inputFile = null;
        Boolean columnNamesFromFirstRow = null;
        byte[] response = api.convertDataCsvToXml(inputFile, columnNamesFromFirstRow);

        // TODO: test validations
    }
    
    /**
     * Convert JSON String to XML conversion
     *
     * Convert a JSON object into XML
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataJsonStringToXmlTest() throws IOException {
        String jsonString = null;
        Object response = api.convertDataJsonStringToXml(jsonString);

        // TODO: test validations
    }
    
    /**
     * Convert JSON Object to XML conversion
     *
     * Convert a JSON object into XML
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataJsonToXmlTest() throws IOException {
        Object jsonObject = null;
        byte[] response = api.convertDataJsonToXml(jsonObject);

        // TODO: test validations
    }
    
    /**
     * Convert Excel (97-2003) XLS to JSON conversion
     *
     * Convert an Excel (97-2003) XLS file to a JSON object array
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXlsToJsonTest() throws IOException {
        File inputFile = null;
        Object response = api.convertDataXlsToJson(inputFile);

        // TODO: test validations
    }
    
    /**
     * Convert Excel XLSX to JSON conversion
     *
     * Convert an Excel XLSX file to a JSON object array
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXlsxToJsonTest() throws IOException {
        File inputFile = null;
        byte[] response = api.convertDataXlsxToJson(inputFile);

        // TODO: test validations
    }
    
    /**
     * Convert Excel XLSX to XML conversion
     *
     * Convert an Excel XLSX file to a XML file
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXlsxToXmlTest() throws IOException {
        File inputFile = null;
        byte[] response = api.convertDataXlsxToXml(inputFile);

        // TODO: test validations
    }
    
    /**
     * Adds an attribute to all XML nodes matching XPath expression
     *
     * Return the reuslts of editing an XML document by adding an attribute to all of the nodes that match an input XPath expression.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXmlEditAddAttributeWithXPathTest() throws IOException {
        String xpathExpression = null;
        String xmlAttributeName = null;
        String xmlAttributeValue = null;
        File inputFile = null;
        XmlAddAttributeWithXPathResult response = api.convertDataXmlEditAddAttributeWithXPath(xpathExpression, xmlAttributeName, xmlAttributeValue, inputFile);

        // TODO: test validations
    }
    
    /**
     * Adds an XML node as a child to XML nodes matching XPath expression
     *
     * Return the reuslts of editing an XML document by adding an XML node as a child to all of the nodes that match an input XPath expression.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXmlEditAddChildWithXPathTest() throws IOException {
        String xpathExpression = null;
        String xmlNodeToAdd = null;
        File inputFile = null;
        XmlAddChildWithXPathResult response = api.convertDataXmlEditAddChildWithXPath(xpathExpression, xmlNodeToAdd, inputFile);

        // TODO: test validations
    }
    
    /**
     * Removes, deletes all children of nodes matching XPath expression, but does not remove the nodes
     *
     * Return the reuslts of editing an XML document by removing all child nodes of the nodes that match an input XPath expression.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXmlEditRemoveAllChildNodesWithXPathTest() throws IOException {
        String xpathExpression = null;
        File inputFile = null;
        XmlRemoveAllChildrenWithXPathResult response = api.convertDataXmlEditRemoveAllChildNodesWithXPath(xpathExpression, inputFile);

        // TODO: test validations
    }
    
    /**
     * Replaces XML nodes matching XPath expression with new node
     *
     * Return the reuslts of editing an XML document by replacing all of the nodes that match an input XPath expression with a new XML node expression.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXmlEditReplaceWithXPathTest() throws IOException {
        String xpathExpression = null;
        String xmlNodeReplacement = null;
        File inputFile = null;
        XmlReplaceWithXPathResult response = api.convertDataXmlEditReplaceWithXPath(xpathExpression, xmlNodeReplacement, inputFile);

        // TODO: test validations
    }
    
    /**
     * Sets the value contents of XML nodes matching XPath expression
     *
     * Return the reuslts of editing an XML document by setting the contents of all of the nodes that match an input XPath expression.  Supports elements and attributes.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXmlEditSetValueWithXPathTest() throws IOException {
        String xpathExpression = null;
        String xmlValue = null;
        File inputFile = null;
        XmlSetValueWithXPathResult response = api.convertDataXmlEditSetValueWithXPath(xpathExpression, xmlValue, inputFile);

        // TODO: test validations
    }
    
    /**
     * Filter, select XML nodes using XPath expression, get results
     *
     * Return the reuslts of filtering, selecting an XML document with an XPath expression
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXmlFilterWithXPathTest() throws IOException {
        String xpathExpression = null;
        File inputFile = null;
        XmlFilterWithXPathResult response = api.convertDataXmlFilterWithXPath(xpathExpression, inputFile);

        // TODO: test validations
    }
    
    /**
     * Query an XML file using XQuery query, get results
     *
     * Return the reuslts of querying a single XML document with an XQuery expression.  Supports XQuery 3.1 and earlier.  This API is optimized for a single XML document as input.  Provided XML document is automatically loaded as the default context; to access elements in the document, simply refer to them without a document reference, such as bookstore/book
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXmlQueryWithXQueryTest() throws IOException {
        String xquery = null;
        File inputFile = null;
        XmlQueryWithXQueryResult response = api.convertDataXmlQueryWithXQuery(xquery, inputFile);

        // TODO: test validations
    }
    
    /**
     * Query multiple XML files using XQuery query, get results
     *
     * Return the reuslts of querying an XML document with an XQuery expression.  Supports XQuery 3.1 and earlier.  This API is optimized for multiple XML documents as input.  You can refer to the contents of a given document by name, for example doc(\&quot;books.xml\&quot;) or doc(\&quot;restaurants.xml\&quot;) if you included two input files named books.xml and restaurants.xml.  If input files contain no file name, they will default to file names input1.xml, input2.xml and so on.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXmlQueryWithXQueryMultiTest() throws IOException {
        String xquery = null;
        File inputFile1 = null;
        File inputFile2 = null;
        File inputFile3 = null;
        File inputFile4 = null;
        File inputFile5 = null;
        File inputFile6 = null;
        File inputFile7 = null;
        File inputFile8 = null;
        File inputFile9 = null;
        File inputFile10 = null;
        XmlQueryWithXQueryMultiResult response = api.convertDataXmlQueryWithXQueryMulti(xquery, inputFile1, inputFile2, inputFile3, inputFile4, inputFile5, inputFile6, inputFile7, inputFile8, inputFile9, inputFile10);

        // TODO: test validations
    }
    
    /**
     * Remove, delete XML nodes and items matching XPath expression
     *
     * Return the reuslts of editing an XML document by removing all of the nodes that match an input XPath expression
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXmlRemoveWithXPathTest() throws IOException {
        String xpathExpression = null;
        File inputFile = null;
        XmlRemoveWithXPathResult response = api.convertDataXmlRemoveWithXPath(xpathExpression, inputFile);

        // TODO: test validations
    }
    
    /**
     * Convert XML to JSON conversion
     *
     * Convert an XML string or file into JSON
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXmlToJsonTest() throws IOException {
        File inputFile = null;
        Object response = api.convertDataXmlToJson(inputFile);

        // TODO: test validations
    }
    
    /**
     * Transform XML document file with XSLT into a new XML document
     *
     * Convert an XML string or file into JSON
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void convertDataXmlTransformWithXsltToXmlTest() throws IOException {
        File inputFile = null;
        File transformFile = null;
        byte[] response = api.convertDataXmlTransformWithXsltToXml(inputFile, transformFile);

        // TODO: test validations
    }
    
}
