/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cloudmersive.client.gac;

import com.cloudmersive.client.gac.model.Base64DecodeRequest;
import com.cloudmersive.client.gac.model.Base64DecodeResponse;
import com.cloudmersive.client.gac.model.Base64DetectRequest;
import com.cloudmersive.client.gac.model.Base64DetectResponse;
import com.cloudmersive.client.gac.model.Base64EncodeRequest;
import com.cloudmersive.client.gac.model.Base64EncodeResponse;
import com.cloudmersive.client.gac.model.ChangeLineEndingResponse;
import com.cloudmersive.client.gac.model.DetectLineEndingsResponse;
import java.io.File;
import com.cloudmersive.client.gac.model.FindStringRegexRequest;
import com.cloudmersive.client.gac.model.FindStringRegexResponse;
import com.cloudmersive.client.gac.model.FindStringSimpleRequest;
import com.cloudmersive.client.gac.model.FindStringSimpleResponse;
import com.cloudmersive.client.gac.model.RemoveHtmlFromTextRequest;
import com.cloudmersive.client.gac.model.RemoveHtmlFromTextResponse;
import com.cloudmersive.client.gac.model.RemoveWhitespaceFromTextRequest;
import com.cloudmersive.client.gac.model.RemoveWhitespaceFromTextResponse;
import com.cloudmersive.client.gac.model.ReplaceStringRegexRequest;
import com.cloudmersive.client.gac.model.ReplaceStringRegexResponse;
import com.cloudmersive.client.gac.model.ReplaceStringSimpleRequest;
import com.cloudmersive.client.gac.model.ReplaceStringSimpleResponse;
import com.cloudmersive.client.gac.model.TextEncodingDetectResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EditTextApi
 */
@Ignore
public class EditTextApiTest {

    private final EditTextApi api = new EditTextApi();

    
    /**
     * Base 64 decode, convert base 64 string to binary content
     *
     * Decodes / converts base 64 UTF-8 text string to binary content
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextBase64DecodeTest() throws IOException {
        Base64DecodeRequest request = null;
        Base64DecodeResponse response = api.editTextBase64Decode(request);

        // TODO: test validations
    }
    
    /**
     * Detect, check if text string is base 64 encoded
     *
     * Checks, detects if input string is base 64 encoded
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextBase64DetectTest() throws IOException {
        Base64DetectRequest request = null;
        Base64DetectResponse response = api.editTextBase64Detect(request);

        // TODO: test validations
    }
    
    /**
     * Base 64 encode, convert binary or file data to a text string
     *
     * Encodes / converts binary or file data to a text string
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextBase64EncodeTest() throws IOException {
        Base64EncodeRequest request = null;
        Base64EncodeResponse response = api.editTextBase64Encode(request);

        // TODO: test validations
    }
    
    /**
     * Set, change line endings of a text file
     *
     * Sets the line ending type of a text file; set to Windows, Unix or Mac.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextChangeLineEndingsTest() throws IOException {
        String lineEndingType = null;
        File inputFile = null;
        ChangeLineEndingResponse response = api.editTextChangeLineEndings(lineEndingType, inputFile);

        // TODO: test validations
    }
    
    /**
     * Detect line endings of a text file
     *
     * Detect line ending type (Windows, Unix or Mac) of an input file.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextDetectLineEndingsTest() throws IOException {
        File inputFile = null;
        DetectLineEndingsResponse response = api.editTextDetectLineEndings(inputFile);

        // TODO: test validations
    }
    
    /**
     * Find a regular expression regex in text input
     *
     * Find all occurrences of the input regular expression in the input content, and returns the matches
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextFindRegexTest() throws IOException {
        FindStringRegexRequest request = null;
        FindStringRegexResponse response = api.editTextFindRegex(request);

        // TODO: test validations
    }
    
    /**
     * Find a string in text input
     *
     * Finds all occurrences of the input string in the input content, and returns the matches
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextFindSimpleTest() throws IOException {
        FindStringSimpleRequest request = null;
        FindStringSimpleResponse response = api.editTextFindSimple(request);

        // TODO: test validations
    }
    
    /**
     * Remove whitespace from text string
     *
     * Removes all whitespace from text, leaving behind only non-whitespace characters.  Whitespace includes newlines, spaces and other whitespace characters.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextRemoveAllWhitespaceTest() throws IOException {
        RemoveWhitespaceFromTextRequest request = null;
        RemoveWhitespaceFromTextResponse response = api.editTextRemoveAllWhitespace(request);

        // TODO: test validations
    }
    
    /**
     * Remove HTML from text string
     *
     * Removes HTML from text, leaving behind only text.  Formatted text will become plain text.  Important for protecting against HTML and Cross-Site-Scripting attacks.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextRemoveHtmlTest() throws IOException {
        RemoveHtmlFromTextRequest request = null;
        RemoveHtmlFromTextResponse response = api.editTextRemoveHtml(request);

        // TODO: test validations
    }
    
    /**
     * Replace a string in text with a regex regular expression string
     *
     * Replaces all occurrences of the input regular expression regex string in the input content, and returns the result
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextReplaceRegexTest() throws IOException {
        ReplaceStringRegexRequest request = null;
        ReplaceStringRegexResponse response = api.editTextReplaceRegex(request);

        // TODO: test validations
    }
    
    /**
     * Replace a string in text with another string value
     *
     * Replaces all occurrences of the input string in the input content, and returns the result
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextReplaceSimpleTest() throws IOException {
        ReplaceStringSimpleRequest request = null;
        ReplaceStringSimpleResponse response = api.editTextReplaceSimple(request);

        // TODO: test validations
    }
    
    /**
     * Detect text encoding of file
     *
     * Checks text encoding of file
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextTextEncodingDetectTest() throws IOException {
        File inputFile = null;
        TextEncodingDetectResponse response = api.editTextTextEncodingDetect(inputFile);

        // TODO: test validations
    }
    
    /**
     * Trim leading and trailing whitespace from text string
     *
     * Trim leading and trailing whitespace from text, leaving behind a trimmed string.  Whitespace includes newlines, spaces and other whitespace characters.
     *
     * @throws IOException
     *          if the Api call fails
     */
    @Test
    public void editTextTrimWhitespaceTest() throws IOException {
        RemoveWhitespaceFromTextRequest request = null;
        RemoveWhitespaceFromTextResponse response = api.editTextTrimWhitespace(request);

        // TODO: test validations
    }
    
}
